# Generated by Django 5.2.3 on 2025-06-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentplanpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentplanpayment',
            name='payment_plan',
        ),
        migrations.DeleteModel(
            name='InsuranceClaim',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.DeleteModel(
            name='PaymentPlanPayment',
        ),
    ]
